# check not existance of out\westlakethesis.fls
if (!(Test-Path -Path "out\westlakethesis.fls")) {
    Write-Host "Cannot find file 'out/westlakethesis.fls', which is generated by latexmk"
    Write-Host "Please use 'latexmk' command to compile westlakethesis first, then run"
    Write-Host "this script under the project root dir to count words"
    exit 1
}

# basename list of files to be excluded
$excluded="thanksto.tex", "acknowledgement.tex", "review.tex", "original.tex", "cv.tex"

# a function to get file basename with UNIX path separator
function Get-Basename {
    param (
        [string]$path
    )
    $basename = $path -replace "^.+/", ""
    return $basename
}

# get unique file list ending with .tex existed in 'body/' dir
# exclude files whose basename in $excluded list from westlakethesis.fls
Get-Content -Path "out\westlakethesis.fls" `
    | Where-Object { $_ -match "INPUT" } `
    | ForEach-Object { $_.split(" ")[1] } `
    | Where-Object { $_ -match "body/.+\.tex$" } `
    | Where-Object { (Get-Basename $_) -notin $excluded } `
    | Select-Object -Unique `
    | ForEach-Object { "\input{$_}" } `
    | Out-File -FilePath "out\westlakethesis.wordcnt" -Encoding UTF8

# count words by texcount
texcount out/westlakethesis.wordcnt -inc


